// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVB09QVh9YizQ7p1YXGcQWQ_43NV6f0SE',
    appId: '1:76007537447:web:57a848570f39091b5a4702',
    messagingSenderId: '76007537447',
    projectId: 'congestion-free',
    authDomain: 'avahanaa.com',
    storageBucket: 'congestion-free.firebasestorage.app',
    measurementId: 'G-5PNGPJZL6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAcPArEa-Ej3gMDYaWJx5zlHYU7Mu8Gf4',
    appId: '1:76007537447:android:031310cc19281fb65a4702',
    messagingSenderId: '76007537447',
    projectId: 'congestion-free',
    storageBucket: 'congestion-free.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhdIgfzdE7t13IhNCQHNgv82hCJckpyNE',
    appId: '1:76007537447:ios:73061ea3266dc0f75a4702',
    messagingSenderId: '76007537447',
    projectId: 'congestion-free',
    storageBucket: 'congestion-free.firebasestorage.app',
    iosBundleId: 'com.example.congestionFree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhdIgfzdE7t13IhNCQHNgv82hCJckpyNE',
    appId: '1:76007537447:ios:73061ea3266dc0f75a4702',
    messagingSenderId: '76007537447',
    projectId: 'congestion-free',
    storageBucket: 'congestion-free.firebasestorage.app',
    iosBundleId: 'com.example.congestionFree',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVB09QVh9YizQ7p1YXGcQWQ_43NV6f0SE',
    appId: '1:76007537447:web:986cf5646199f1e25a4702',
    messagingSenderId: '76007537447',
    projectId: 'congestion-free',
    authDomain: 'avahanaa.com',
    storageBucket: 'congestion-free.firebasestorage.app',
    measurementId: 'G-1P170L5YK7',
  );
}
